name: Test

on: 
    push:
        branches:
            - main
        paths:
            - '**.py'
            - '**.yml'
    pull_request:
        branches: 
            - main
        paths: 
            - '**.py'
            - '**.yml'

jobs:
    test:
        runs-on: ubuntu-22.04

        steps:
          - name: Checkout repo
            uses: actions/checkout@v4.2.2
        
          - name: Install the latest version of uv and set the python version
            uses: astral-sh/setup-uv@v6
            with:
              python-version: '3.12'
        
          - name: Run tests
            run: uv run pytest -vv
          
          - name: Run ruff check
            run: uv run ruff check